# Numpy

NUMPY is the fundamental package for scientific computing in Python. NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python's built-in sequences.

 


## why numpy?
* many functionalities in numpy are coded/optimised in c which are very fast when compared to python functions
* NUMPY is backbone to many sentific calucations 



#### Getting started with python numy 
    In numpy we mostly work with arrays.By default arrays are stored as ndarray(N-Dimensional array)
    and numpy supports all the datatypes of python
    

In [1]:
#import numpy
import numpy as np

In [2]:
#creating array (type-1)
array1=np.array([1,2,3,4,5]) #1-d array



In [3]:
#print array
array1

array([1, 2, 3, 4, 5])

In [6]:
#2-d array
array2=np.array([[1,2,3,4,5],
                [12,43,1324,123,4314]])

In [19]:
array2

array([[   1,    2,    3,    4,    5],
       [  12,   43, 1324,  123, 4314]])

In [20]:
#3-d array
array3=np.array([[1,2,3,4,5],
                [1,3,4,6,5],
                [12,43,1324,123,4314]])
#print array
array3

array([[   1,    2,    3,    4,    5],
       [   1,    3,    4,    6,    5],
       [  12,   43, 1324,  123, 4314]])

In [21]:
#finding type of array
type(array2)

numpy.ndarray

##### attributes in NumPy

In [22]:
#shape
#shape returns the number of rows and columns in the array
array2.shape


(2, 5)

In [23]:
array2.shape

(2, 5)

In [24]:
#size
#size returns the number of elements in the array
array2.size,array1.size,array3.size

(10, 5, 15)

In [25]:
#ndim
#ndim returns the dimensions of the array
array2.ndim,array3.ndim,array1.ndim

(2, 2, 1)

In [26]:
#creating arrays type-2
#ones
#ones will create array with only ones 
#syntax
#arrayname=numpy.ones(rows,columns)
ones=np.ones((5,3))

In [27]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
#zeros
#zeros will create array with only zeros 
#syntax
#arrayname=numpy.zeros(rows,columns)
zeros=np.zeros((5,3))

In [29]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
#arange
#arange will create array within the range
#syntax
#arrayname=numpy.arange(start,stop,step)
array=np.arange(0,10,2)

array

array([0, 2, 4, 6, 8])

In [36]:
#random array
#random will create array with random numbers 
#syntax
#arrayname=numpy.random.randint(min,max,size=(row,columns))
randarray=np.random.randint(0,high=10,size=(5,3))

In [37]:
randarray

array([[9, 8, 7],
       [6, 5, 3],
       [2, 5, 6],
       [5, 4, 9],
       [1, 9, 1]])