In [2]:
import numpy as np


In [3]:
array1=np.random.randint(1,high=12,size=(3,3))

In [4]:
array1

array([[10, 10, 10],
       [ 6, 11,  5],
       [10, 10,  5]])

In [5]:
array1

array([[10, 10, 10],
       [ 6, 11,  5],
       [10, 10,  5]])

In [8]:
#find unique values in array
np.unique(array1)


array([ 5,  6, 10, 11])

#### viewing data in the array and matrics

In [15]:
array1[2][2],array1[1]

(5, array([ 6, 11,  5]))

In [40]:
array2=np.array([
                [[1,2,3,4,5],
                [2,3,4,5,6],
                [3,4,5,6,7],
                [33,21,21,41,12]],
    
                [[9,8,7,6,5],
                [8,7,6,5,4],
                [7,6,5,4,3],
                [12,12,13,14,14]]
    
                ])

In [41]:
array2.ndim,array2.shape


(3, (2, 4, 5))

In [42]:
#viewing 1st matrics/array
array2[0]

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [33, 21, 21, 41, 12]])

In [43]:
#viewing 1st row in the 1st matrics/array type-1
array2[0][0]

array([1, 2, 3, 4, 5])

In [57]:

#viewing 1st row in the 1st matrics/array type-2(slicing)
#SYNTAX
#arrayname[matrix,column,row]
array2[:1 , 2:3 ,:2]

array([[[3, 4]]])

In [59]:
#viewing elements in two matrix third row,1and2 columns
array2[:2 , 2:3 ,:2]

array([[[3, 4]],

       [[7, 6]]])

In [85]:
#syntax
#arrayname=np.random.randint(low=1,high=10,size=(no of dimension,no_of_matrics in one dimension,no_of_rows,no_of_columns))
np.random.seed(0)# with seed same number will apper everytime we run random.randint  
array3=np.random.randint(1,high=10,size=(3,3,4,5))

In [74]:
array3

array([[[[1, 7, 4, 8, 5],
         [4, 9, 5, 3, 2],
         [3, 4, 2, 1, 4],
         [7, 2, 7, 8, 8]],

        [[4, 3, 2, 7, 3],
         [8, 9, 8, 6, 7],
         [7, 4, 2, 8, 7],
         [2, 7, 1, 7, 8]],

        [[3, 1, 9, 1, 2],
         [7, 2, 7, 1, 1],
         [9, 6, 3, 4, 9],
         [6, 1, 4, 2, 5]]],


       [[[7, 7, 7, 1, 4],
         [6, 5, 9, 2, 6],
         [2, 5, 3, 8, 4],
         [9, 4, 7, 7, 8]],

        [[9, 2, 5, 1, 6],
         [5, 9, 4, 3, 5],
         [5, 2, 2, 2, 2],
         [5, 6, 4, 1, 2]],

        [[8, 3, 7, 7, 6],
         [6, 3, 3, 1, 7],
         [3, 8, 1, 2, 3],
         [4, 1, 8, 2, 3]]],


       [[[2, 2, 5, 5, 9],
         [2, 1, 2, 4, 6],
         [5, 8, 9, 2, 7],
         [2, 2, 9, 9, 5]],

        [[2, 7, 9, 6, 9],
         [8, 5, 1, 1, 3],
         [7, 8, 4, 1, 3],
         [5, 5, 2, 7, 4]],

        [[1, 7, 3, 5, 6],
         [4, 2, 9, 4, 3],
         [2, 8, 8, 7, 5],
         [6, 6, 4, 9, 3]]]])

In [86]:
array3.shape,array3.ndim

((3, 3, 4, 5), 4)

In [87]:
#find elemnts of last two rows and last two columns of every matrix
array3[:,:,2:,3:]

array([[[[2, 7],
         [2, 6]],

        [[4, 8],
         [5, 8]],

        [[5, 9],
         [4, 7]]],


       [[[9, 5],
         [6, 1]],

        [[1, 8],
         [8, 3]],

        [[4, 1],
         [7, 4]]],


       [[[9, 5],
         [4, 7]],

        [[6, 8],
         [9, 7]],

        [[1, 9],
         [9, 3]]]])

In [88]:
array3

array([[[[6, 1, 4, 4, 8],
         [4, 6, 3, 5, 8],
         [7, 9, 9, 2, 7],
         [8, 8, 9, 2, 6]],

        [[9, 5, 4, 1, 4],
         [6, 1, 3, 4, 9],
         [2, 4, 4, 4, 8],
         [1, 2, 1, 5, 8]],

        [[4, 3, 8, 3, 1],
         [1, 5, 6, 6, 7],
         [9, 5, 2, 5, 9],
         [2, 2, 8, 4, 7]]],


       [[[8, 3, 1, 4, 6],
         [5, 5, 7, 5, 5],
         [4, 5, 5, 9, 5],
         [4, 8, 6, 6, 1]],

        [[2, 6, 4, 1, 6],
         [1, 2, 3, 5, 3],
         [1, 4, 3, 1, 8],
         [6, 1, 3, 8, 3]],

        [[3, 4, 4, 3, 4],
         [5, 2, 3, 2, 5],
         [7, 9, 3, 4, 1],
         [1, 7, 1, 7, 4]]],


       [[[4, 9, 9, 9, 3],
         [4, 3, 1, 9, 9],
         [4, 9, 3, 9, 5],
         [4, 1, 5, 4, 7]],

        [[9, 1, 9, 6, 1],
         [7, 6, 4, 2, 9],
         [1, 5, 7, 6, 8],
         [9, 9, 3, 9, 7]],

        [[7, 2, 7, 9, 9],
         [4, 3, 4, 7, 4],
         [7, 6, 8, 1, 9],
         [5, 7, 6, 9, 3]]]])

In [89]:
array3.shape

(3, 3, 4, 5)

In [91]:
array3[2,2,0]

array([7, 2, 7, 9, 9])

#### manipulating arrays 

In [95]:
'''operations on arrays
- addition/sum
- suntraction/differfence
- product/multiplaction
- division /reminder'''
#CREATING ARRAYS
np.random.seed(0)
arr1=np.random.randint(1,high=9,size=(3,3))
arr2=np.random.randint(1,high=9,size=(3,3))



In [94]:
arr1

array([[5, 8, 6],
       [1, 4, 4],
       [4, 8, 2]])

In [96]:
arr2

array([[4, 6, 3],
       [5, 8, 7],
       [1, 1, 5]])

In [101]:
#addition
#arr1+arr2
np.add(arr1,arr2)

array([[ 9, 14,  9],
       [ 6, 12, 11],
       [ 5,  9,  7]])

In [102]:
#SUBTRACTION 
#arr1-arr2
np.subtract(arr1,arr2)


array([[ 1,  2,  3],
       [-4, -4, -3],
       [ 3,  7, -3]])

In [106]:
#PRODUCT
#arr1*arr2
np.multiply(arr1,arr2)

array([[20, 48, 18],
       [ 5, 32, 28],
       [ 4,  8, 10]])

In [112]:
#arr1//arr2(floor division)
#arr1/arr2(division)
a=np.floor_divide(arr1,arr2
               )
b=np.divide(arr1,arr2)
a,b

(array([[1, 1, 2],
        [0, 0, 0],
        [4, 8, 0]], dtype=int32),
 array([[1.25      , 1.33333333, 2.        ],
        [0.2       , 0.5       , 0.57142857],
        [4.        , 8.        , 0.4       ]]))

In [114]:
#arr1**2(squaring)
np.square(arr1)

array([[25, 64, 36],
       [ 1, 16, 16],
       [16, 64,  4]], dtype=int32)

In [116]:
#sum- returns sum of allo the elements in the array/matrix
arr1.sum()


42

In [118]:
arr1.min()

1

In [119]:
arr1.max()

8

In [121]:
arr1.mean()

4.666666666666667

In [173]:
#dot product
#WHEN PERFORMING DOT THE NUMBER OF ROWS OF M1 SHOULD BE EQUAL TO 
np.random.seed(0)
aa1=np.random.randint(1,high=9,size=(5,3))
aa2=np.random.randint(1,high=9,size=(1,3))

In [176]:
#np.dot(aa1,aa2.reshape(3,1)) or  
np.dot(aa1,aa2.T) #T for transpose 

array([[43],
       [25],
       [22],
       [25],
       [48]])

#### comparison operations


In [191]:
np.random.seed(0)
a1=np.random.randint(1,high=9,size=(5,3))
a2=np.random.randint(1,high=9,size=(5,3))

In [192]:
a1>a2

array([[ True,  True,  True],
       [False,  True, False],
       [False, False, False],
       [ True,  True, False],
       [ True,  True,  True]])

In [193]:
a1<a2

array([[False, False, False],
       [ True, False,  True],
       [ True, False,  True],
       [False, False,  True],
       [False, False, False]])

In [194]:
a1==a2

array([[False, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [195]:
a1!=a2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [196]:
a1>5

array([[False,  True,  True],
       [False, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True,  True]])

#### sorting arrays



In [197]:
#sort
#RETURNS THE SORTED ROWS IN THE MATRIX

np.sort(a1)

array([[5, 6, 8],
       [1, 4, 4],
       [2, 4, 8],
       [3, 4, 6],
       [5, 7, 8]])

In [200]:
#argsort
#RETURNS THE INDEX OF THE SORTED ROW IN THE MATRIX
np.argsort(a1)

array([[0, 2, 1],
       [0, 1, 2],
       [2, 0, 1],
       [2, 0, 1],
       [0, 2, 1]], dtype=int64)